### ISSUE TITLE
[Ring Submission]  Simple Sharp Ring

### ISSUE THREAD

**Issue by joeundsoo** [ChasarooniZ/More-Dynamic-Token-Rings#3]
### Ring Name
Simple Sharp Ring

### Ring Licensing
I made it, no need to worry about licensing.

### Plug your Stuff
Don't have anything to plug.

### Misc
GitHub doesn't support the upload of webp, so I had to convert the ring to png.
![Simple_Sharp_Ring](https://github.com/user-attachments/assets/11558629-630a-458d-806f-dfa3d66db895)

**Comment by ChasarooniZ** [comment]
Ah okay, that's cringe github doesn't support that but its fine

**Comment by joeundsoo** [comment]
Isn't it possible to have two different reactive parts of the ring? As it stands now, just the whole ring is being colored and stuff, which wasn't my intention. If it's not possible, I can make modifications, so just the inside of the ring will be the reactive part.

**Comment by ChasarooniZ** [comment]
Uhh I don't believe so? but i see what you mean by that

**Comment by ChasarooniZ** [comment]
I'll try some json change

**Comment by ChasarooniZ** [comment]
Figured it out, will need to redo some of your ring border
![image](https://github.com/user-attachments/assets/029c0a5e-cd3c-4917-8c56-265e13cdfe88)

**Comment by ChasarooniZ** [comment]
you basically need to cheat the color system by having the "ring" be mostly transparent

**Comment by ChasarooniZ** [comment]
_at least afaik_

**Comment by ChasarooniZ** [comment]
![image](https://github.com/user-attachments/assets/2fd5f1b0-ea09-4d9f-8346-bb1a4c0be3b6)
Fixed issue

**Comment by ChasarooniZ** [comment]
Will be in next update
