### ISSUE TITLE
[Feature] Update Polish translate

### ISSUE THREAD

**Issue by Lioheart** [ChasarooniZ/More-Dynamic-Token-Rings#37]
Hello,

I add updated Polish translate below.
[pl.json](https://github.com/user-attachments/files/16894762/pl.json)

**Comment by ChasarooniZ** [comment]
Hey, in the future I can add these faster if you make a PR which you can do as follows:

Click edit the file for the `pl.json`
![image](https://github.com/user-attachments/assets/244cff12-6750-4fff-8485-8634b42449f0)
Replace the file text with your `pl.json`, then click `Commit Cahnges` a pop up appears and then click the `Create a new branch and start a pull request`
![image](https://github.com/user-attachments/assets/e373578c-6653-44dd-8455-a898dd97d1ef)
Make the PR, update title and submit 
![image](https://github.com/user-attachments/assets/159b3998-65da-4d45-9641-9b88cfcb8f0c)



If you do this I can just accept the PR as opposed to having to have the repo up on my PC etc.!

Ty as always for your translations!

**Comment by Lioheart** [comment]
Understand, thanks.

**Comment by ChasarooniZ** [comment]
If it ends up being too much you can still just leave an issue like you've been doing, the PR method will just let me respond a bit faster
