### ISSUE TITLE
[Bug] Custom ring is not showing up on the player's client

### ISSUE THREAD

**Issue by Stonedtroll** [ChasarooniZ/More-Dynamic-Token-Rings#38]
**Describe the bug**
Custom ring is not showing up on the player's client but is showing correctly on the GM's client.

**To Reproduce**
1. Create am custom ring.
2. Check that an actor has the correct ring on the GM's client.
3. Check the same actor on the player's client.

**Expected behavior**
Custom ring should be showing on all clients.

**Comment by ChasarooniZ** [comment]
Oh i think i know the issue, i'll look into it!

**Comment by ChasarooniZ** [comment]
It should be fixed!

**Comment by Stonedtroll** [comment]
Confirmed. Thank you!
